package com.zahangir.model;
// Generated Jul 12, 2017 5:29:19 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

/**
 * Indoor generated by hbm2java
 */
@Entity
public class Indoor implements java.io.Serializable {

    private Integer indoorId;
    @OneToOne(orphanRemoval = true)
    private Admission admission;
    @OneToOne(orphanRemoval = true)
    private Specialist specialist;
    @NotNull(message = "You must check any department")
    private String indoorDepartment;
    @NotNull(message = "You must check any indoor type")
    private String indoorType;

    public Indoor() {
    }

    public Indoor(Admission admission, Specialist specialist, String indoorDepartment, String indoorType) {
        this.admission = admission;
        this.specialist = specialist;
        this.indoorDepartment = indoorDepartment;
        this.indoorType = indoorType;
    }

    public Integer getIndoorId() {
        return this.indoorId;
    }

    public void setIndoorId(Integer indoorId) {
        this.indoorId = indoorId;
    }

    public Admission getAdmission() {
        return this.admission;
    }

    public void setAdmission(Admission admission) {
        this.admission = admission;
    }

    public Specialist getSpecialist() {
        return this.specialist;
    }

    public void setSpecialist(Specialist specialist) {
        this.specialist = specialist;
    }

    public String getIndoorDepartment() {
        return this.indoorDepartment;
    }

    public void setIndoorDepartment(String indoorDepartment) {
        this.indoorDepartment = indoorDepartment;
    }

    public String getIndoorType() {
        return this.indoorType;
    }

    public void setIndoorType(String indoorType) {
        this.indoorType = indoorType;
    }

}
