package com.zahangir.model;
// Generated Jul 10, 2017 4:54:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Indoor generated by hbm2java
 */
public class Indoor  implements java.io.Serializable {


     private Integer indoorId;
     private Admission admission;
     private String indoorDepartment;
     private Set specialists = new HashSet(0);

    public Indoor() {
    }

	
    public Indoor(Admission admission, String indoorDepartment) {
        this.admission = admission;
        this.indoorDepartment = indoorDepartment;
    }
    public Indoor(Admission admission, String indoorDepartment, Set specialists) {
       this.admission = admission;
       this.indoorDepartment = indoorDepartment;
       this.specialists = specialists;
    }
   
    public Integer getIndoorId() {
        return this.indoorId;
    }
    
    public void setIndoorId(Integer indoorId) {
        this.indoorId = indoorId;
    }
    public Admission getAdmission() {
        return this.admission;
    }
    
    public void setAdmission(Admission admission) {
        this.admission = admission;
    }
    public String getIndoorDepartment() {
        return this.indoorDepartment;
    }
    
    public void setIndoorDepartment(String indoorDepartment) {
        this.indoorDepartment = indoorDepartment;
    }
    public Set getSpecialists() {
        return this.specialists;
    }
    
    public void setSpecialists(Set specialists) {
        this.specialists = specialists;
    }




}


