package com.zahangir.model;
// Generated Jul 12, 2017 5:29:19 PM by Hibernate Tools 4.3.1


import com.zahangir.mycustonvalidator.Phone;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Mi generated by hbm2java
 */
@Entity
public class Mi  implements java.io.Serializable {


     private Integer miId;
     @Size(max = 30, min = 3, message = "Name must be between {min} to {max} characters")
     private String miName;
     @NotEmpty(message = "You must select your Qualification")
     private String miQualification;
     @Size(min = 5, max = 60, message = "Address must be between {min} to {max} characters")
     private String miAddress;
     @NotNull(message = "You must check your gender")
     private String miGender;
     @Phone(message = "Contact no is not formated")
     private String miContactNo;
     @Email(message = "Email format not valid")
     private String miEmail;
     @NotEmpty(message = "You must select your time")
     private String miTime;
     @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true, mappedBy="mi")
     private Set<Outdoor> outdoors = new HashSet(0);

    public Mi() {
    }

	
    public Mi(String miName, String miQualification, String miAddress, String miGender, String miContactNo, String miEmail, String miTime) {
        this.miName = miName;
        this.miQualification = miQualification;
        this.miAddress = miAddress;
        this.miGender = miGender;
        this.miContactNo = miContactNo;
        this.miEmail = miEmail;
        this.miTime = miTime;
    }
    public Mi(String miName, String miQualification, String miAddress, String miGender, String miContactNo, String miEmail, String miTime, Set outdoors) {
       this.miName = miName;
       this.miQualification = miQualification;
       this.miAddress = miAddress;
       this.miGender = miGender;
       this.miContactNo = miContactNo;
       this.miEmail = miEmail;
       this.miTime = miTime;
       this.outdoors = outdoors;
    }
   
    public Integer getMiId() {
        return this.miId;
    }
    
    public void setMiId(Integer miId) {
        this.miId = miId;
    }
    public String getMiName() {
        return this.miName;
    }
    
    public void setMiName(String miName) {
        this.miName = miName;
    }
    public String getMiQualification() {
        return this.miQualification;
    }
    
    public void setMiQualification(String miQualification) {
        this.miQualification = miQualification;
    }
    public String getMiAddress() {
        return this.miAddress;
    }
    
    public void setMiAddress(String miAddress) {
        this.miAddress = miAddress;
    }
    public String getMiGender() {
        return this.miGender;
    }
    
    public void setMiGender(String miGender) {
        this.miGender = miGender;
    }
    public String getMiContactNo() {
        return this.miContactNo;
    }
    
    public void setMiContactNo(String miContactNo) {
        this.miContactNo = miContactNo;
    }
    public String getMiEmail() {
        return this.miEmail;
    }
    
    public void setMiEmail(String miEmail) {
        this.miEmail = miEmail;
    }
    public String getMiTime() {
        return this.miTime;
    }
    
    public void setMiTime(String miTime) {
        this.miTime = miTime;
    }
    public Set<Outdoor> getOutdoors() {
        return this.outdoors;
    }
    
    public void setOutdoors(Set<Outdoor> outdoors) {
        this.outdoors = outdoors;
    }

}


