package com.zahangir.model;
// Generated Jul 10, 2017 4:54:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

/**
 * Outdoor generated by hbm2java
 */
@Entity
public class Outdoor  implements java.io.Serializable {


     private Integer outdoorId;
    @OneToOne
     private Admission admission;
     private Set mis = new HashSet(0);

    public Outdoor() {
    }

	
    public Outdoor(Admission admission) {
        this.admission = admission;
    }
    public Outdoor(Admission admission, Set mis) {
       this.admission = admission;
       this.mis = mis;
    }
   
    public Integer getOutdoorId() {
        return this.outdoorId;
    }
    
    public void setOutdoorId(Integer outdoorId) {
        this.outdoorId = outdoorId;
    }
    public Admission getAdmission() {
        return this.admission;
    }
    
    public void setAdmission(Admission admission) {
        this.admission = admission;
    }
    public Set getMis() {
        return this.mis;
    }
    
    public void setMis(Set mis) {
        this.mis = mis;
    }




}


