package com.zahangir.model;
// Generated Jul 12, 2017 5:29:19 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Outdoor generated by hbm2java
 */
@Entity
public class Outdoor implements java.io.Serializable {

    private Integer outdoorId;
    @OneToOne(orphanRemoval = true)
    private Admission admission;
    @OneToOne(orphanRemoval = true)
    private Mi mi;
    @NotEmpty(message = "Time can't be empty")
    private String outdoorTime;

    public Outdoor() {
    }

    public Outdoor(Admission admission, Mi mi, String outdoorTime) {
        this.admission = admission;
        this.mi = mi;
        this.outdoorTime = outdoorTime;
    }

    public Integer getOutdoorId() {
        return this.outdoorId;
    }

    public void setOutdoorId(Integer outdoorId) {
        this.outdoorId = outdoorId;
    }

    public Admission getAdmission() {
        return this.admission;
    }

    public void setAdmission(Admission admission) {
        this.admission = admission;
    }

    public Mi getMi() {
        return this.mi;
    }

    public void setMi(Mi mi) {
        this.mi = mi;
    }

    public String getOutdoorTime() {
        return this.outdoorTime;
    }

    public void setOutdoorTime(String outdoorTime) {
        this.outdoorTime = outdoorTime;
    }

}
