package com.zahangir.model;
// Generated Jul 10, 2017 4:54:19 AM by Hibernate Tools 4.3.1



/**
 * Specialist generated by hbm2java
 */
public class Specialist  implements java.io.Serializable {


     private Integer specialistId;
     private Indoor indoor;
     private String specialistName;
     private String specialistQualification;
     private String specialistSpeialty;
     private String specialistAddress;
     private String specialistContactNo;
     private String specialistGender;
     private String specialistEmail;

    public Specialist() {
    }

    public Specialist(Indoor indoor, String specialistName, String specialistQualification, String specialistSpeialty, String specialistAddress, String specialistContactNo, String specialistGender, String specialistEmail) {
       this.indoor = indoor;
       this.specialistName = specialistName;
       this.specialistQualification = specialistQualification;
       this.specialistSpeialty = specialistSpeialty;
       this.specialistAddress = specialistAddress;
       this.specialistContactNo = specialistContactNo;
       this.specialistGender = specialistGender;
       this.specialistEmail = specialistEmail;
    }
   
    public Integer getSpecialistId() {
        return this.specialistId;
    }
    
    public void setSpecialistId(Integer specialistId) {
        this.specialistId = specialistId;
    }
    public Indoor getIndoor() {
        return this.indoor;
    }
    
    public void setIndoor(Indoor indoor) {
        this.indoor = indoor;
    }
    public String getSpecialistName() {
        return this.specialistName;
    }
    
    public void setSpecialistName(String specialistName) {
        this.specialistName = specialistName;
    }
    public String getSpecialistQualification() {
        return this.specialistQualification;
    }
    
    public void setSpecialistQualification(String specialistQualification) {
        this.specialistQualification = specialistQualification;
    }
    public String getSpecialistSpeialty() {
        return this.specialistSpeialty;
    }
    
    public void setSpecialistSpeialty(String specialistSpeialty) {
        this.specialistSpeialty = specialistSpeialty;
    }
    public String getSpecialistAddress() {
        return this.specialistAddress;
    }
    
    public void setSpecialistAddress(String specialistAddress) {
        this.specialistAddress = specialistAddress;
    }
    public String getSpecialistContactNo() {
        return this.specialistContactNo;
    }
    
    public void setSpecialistContactNo(String specialistContactNo) {
        this.specialistContactNo = specialistContactNo;
    }
    public String getSpecialistGender() {
        return this.specialistGender;
    }
    
    public void setSpecialistGender(String specialistGender) {
        this.specialistGender = specialistGender;
    }
    public String getSpecialistEmail() {
        return this.specialistEmail;
    }
    
    public void setSpecialistEmail(String specialistEmail) {
        this.specialistEmail = specialistEmail;
    }




}


