package com.zahangir.model;
// Generated Jul 14, 2017 3:07:59 AM by Hibernate Tools 4.3.1

import com.zahangir.mycustonvalidator.Phone;
import javax.persistence.Entity;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;



/**
 * User generated by hbm2java
 */
@Entity
public class User  implements java.io.Serializable {


     private Integer userId;
     @Size(max = 30, min = 3, message = "Name must be between {min} to {max} characters")
     private String userName;
     @NotEmpty(message = "You must select user role")
     private String userRole;
     @Email(message = "Email format not valid")
     private String userEmail;
     @Phone(message = "Contact no is not formated")
     private String userContactNo;
     @Size(min = 5, max = 60, message = "Address must be between {min} to {max} characters")
     private String userAddress;
     @Size(min = 8, message = "Password at least {min} character")
     private String userPassword;

    public User() {
    }

    public User(String userName, String userRole, String userEmail, String userContactNo, String userAddress, String userPassword) {
       this.userName = userName;
       this.userRole = userRole;
       this.userEmail = userEmail;
       this.userContactNo = userContactNo;
       this.userAddress = userAddress;
       this.userPassword = userPassword;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserContactNo() {
        return this.userContactNo;
    }
    
    public void setUserContactNo(String userContactNo) {
        this.userContactNo = userContactNo;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }




}


