package com.zahangir.model;
// Generated Jul 14, 2017 3:07:59 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;



/**
 * User generated by hbm2java
 */
@Entity
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userRole;
     private String userEmail;
     private String userContactNo;
     private String userAddress;
     private String userPassword;

    public User() {
    }

    public User(String userName, String userRole, String userEmail, String userContactNo, String userAddress, String userPassword) {
       this.userName = userName;
       this.userRole = userRole;
       this.userEmail = userEmail;
       this.userContactNo = userContactNo;
       this.userAddress = userAddress;
       this.userPassword = userPassword;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserContactNo() {
        return this.userContactNo;
    }
    
    public void setUserContactNo(String userContactNo) {
        this.userContactNo = userContactNo;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }




}


